title Core Banking System - Dynamic - Dynamic-001

actor <<Person>>\nUser as User
participant <<Container>>\nAPI as API
participant <<Software System>>\nMessage Broker as Message Broker
participant <<Container>>\nOrder Creator as Order Creator
participant <<Container>>\nOrder Database as Order Database
participant <<Container>>\nOrder Validator as Order Validator
participant <<Container>>\nOrder Placer as Order Placer

User->API: orders/submit(UID)
API->Message Broker: pending creation
Message Broker->Order Creator: consumes CREATED event
Order Creator->Order Database: persists orders
Message Broker->Order Validator: consumes PENDING event
Order Validator->Order Database: PENDING -> REQUESTED*
Message Broker->Order Placer: consumes REQUESTED event
Order Placer->Order Database: REQUESTED -> COMPLETED*